"""
Django settings for freelancehub_backend project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-67luu=dzl_@+982^k@2q23*iufvrv-b#t$cxmwq1()*%ve@1at"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'corsheaders',
    'users.apps.UsersConfig',
    'projects.apps.ProjectsConfig',
    'rest_framework_simplejwt',
    'jobs.apps.JobsConfig',
    'proposals.apps.ProposalsConfig',
    'contracts.apps.ContractsConfig',
    'payments.apps.PaymentsConfig',
    'channels',
    'chats.apps.ChatsConfig',
    'reviews.apps.ReviewsConfig',
    'notifications',
    'disputes',
    # 'rest_framework_simplejwt.token_blacklist'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = "freelancehub_backend.urls"

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Add your frontend URL
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "freelancehub_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# REST Framework settings  (new)
REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],

}

# settings.py
STRIPE_SECRET_KEY = 'sk_test_51RjLoYCWnVkJ7TtuTiztMIb6431zCj66j1b5CrPKEdnVqdvZUHhNedurlb4cxD9rbsMW7kQBQ3AY2Dux3JCJbBSe00fQEWCZdI'  # Use your Stripe test secret key
STRIPE_PUBLISHABLE_KEY = 'pk_test_51RjLoYCWnVkJ7TtuqKFJOerskBE7OikFNOVqd5Q70S3VJ5ObFf3KJBhLeGB6Sy2JfV5Xc14swiUVyysRW3M2czdh00cInFS1Fh'


ASGI_APPLICATION = 'freelancehub_backend.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
        },
    },

    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'postgres',
    #     'USER': 'rejan',
    #     'PASSWORD': 'postgres',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
}

# # DJOSER SETTINGS
# DJOSER = {
#     'LOGIN_FIELD': 'email',
#     'USER_CREATE_PASSWORD_RETYPE': True,
#     'SEND_ACTIVATION_EMAIL': True,
#     'SEND_CONFIRMATION_EMAIL': True,
#     'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}/',
#     'ACTIVATION_URL': 'activate/{uid}/{token}/',
#     'SERIALIZERS': {},
# }
#
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development/testing
# DEFAULT_FROM_EMAIL = 'noreply@yourdomain.com'
CORS_ALLOW_ALL_ORIGINS = True  # For development only!
# Or, for production, use:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:4200",  # Angular default port
#     "http://127.0.0.1:4200",
# SIMPLE_JWT = {
#     "USER_ID_FIELD": "id",
#     "USER_ID_CLAIM": "user_id",
#     "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
#     "TOKEN_USER_CLASS": "users.models.CustomUser",
# }
